language: node_js
node_js:
- '6'
- '7'
cache:
  yarn: true
script:
- npm run test
- npm run build
deploy:
  provider: npm
  email: junrai82@gmail.com
  api_key:
    secure: gqGYr9DzYi4oZhHWjpLjDTQMakWzKib7XvmkHFdgZ0MjnFMF/WwtSwc0Js72AhmC6dtpA1roM/ltLT1LPR7w5HDbiqkhjJuDHKxxx+NPL+1RzXUXYLnryR4tsqKFDeQILC5iw51dzncVbHqoxDssbUC6r6EEqqjG0rD2ic0T7+JuKMrNL2kbuFnNPbIaByMLOu4vPQtUp2xBjyYS1k8pKKbys63umge/x/DqygMzIuIWqyV2wXGmJ9YnssKnlO9FU+31rsA9oQx1anRSa7RHBEhqpBLVWAg+1y6UiaCmyLgM2E5oMJivx5+hlTsJhp2CfqCjNONz6rbtLSY55IYnxOmlMs/8gEWv2C6fhDIGw4oEyLebKy2XR66arShisqcE8CzST+sZDWeXcKQq+8Y27QbszxdRhSo3z0g4UdhTeTtfxXQgABjx8T5Ilw5kgo8MPXv6o5rSmV8dpvPWTRRpUnpEOyRuxbkLo+eqaxoIy+sSJsEeGAfxK3n2IRpYOxQHqbvVUPcNl4uYKvL4Ucd9GFCLmmSS+IUfef9I1kN1ys9Dj+xH2q9eznChvET42PDrc8lN5nLr84GvjDA9s+EJM2Phpc9caogMxMmY32Xb7UFKtbwoHzX8AxXWsUFsHUXltXhbN5Ws5tkev7AgAWANQHVrpgve/VLt64wPbKAeVT4=
  on:
    tags: true
    repo: nodeframe/nfs-seneca
