language: node_js
cache:
  yarn: true
script:
- npm run test
deploy:
  provider: npm
  email: junrai82@gmail.com
  api_key:
    secure: SmpG0t673gBW+/34Mt4LgGbH5keH5KTURJ3i4sLK5uJLxHvEWuH3He6TqA3aWJnUgt8ksckDIlgbZgMPl6x7sxpgcn4MFdlMqbl5kIhK4I6Rb6oYwSBNLfas+4PTeYu+RDC27Df6ItUDjFKu2fTNozyoTfQswOg+JDEwkbHSpqPMYgm2A0VeslHKE8soVG/GChhKtw3mUoFdbGZwPNU3D7Awlj6aGscyD7mZrTNN3MRz1VohDjfTVbSVSiNe1NNxPMm+VvXoYZIKO0TtwdFh3KrTTMmoMfaQ2gSltBomX82EskuHPu2KvRef6/F/DJl/kgJDxeFIyumgkSZwqD89uKmIz9cLaejCzVHkyvt0V2l3pNM9YsGecq4tj80vqc/jXJ/jM+jZHjQRnItydOshefH8wpULLN21LJegr3NGmIJ0LgPOJj25aCyn0PNOMRwxbXvKMadAM/GXD4TMW7k/deBdbBWG6lZAbY3fdg2hhYI0Kxi8DVPGq+Oam8hAqsKow27O2bPawHYlXdGAORlxfz/b9aPH4F+TDDQfRikh4Psrzm0XXgdzrDsuVDXFlsPpwuTACHTm2aRaTw8lEt4RUniAXv2S/TJ1UE043MWlLgp6P5B7l9buHEe1sQkJmfwvvqtcdWk+Lpru74PphS6A4i4fDWoKKMFwraRx9p/ksNc=
  on:
    tags: true
    repo: nodeframe/nfs-seneca
  skip_cleanup: true
